from django.db import models

class weekly_qb_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    game_number = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    date = models.CharField(max_length=255, null=True, blank=True)
    age = models.CharField(max_length=255, null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    opp = models.CharField(max_length=255, null=True, blank=True)
    result = models.CharField(max_length=255, null=True, blank=True)
    completions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    passing_attempts = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    incompletions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    completion_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    passing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    passing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    interceptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    number_of_pick_6 = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    touchdown_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    interception_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    passer_rating = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    sacks = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    sack_yards_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    sack_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    passing_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    air_yards_per_pass_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    passing_adjusted_net_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_per_completion = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    passing_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    intended_air_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    intended_air_yards_per_pass_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    completed_air_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    completed_air_yards_per_completion = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    completed_air_yards_per_pass_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_after_catch = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_after_catch_per_completion = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    passes_batted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    throw_aways = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    spikes = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    passes_dropped = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    percent_of_passes_dropped = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    bad_throws = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    bad_throw_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    passes_on_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    percent_of_passes_on_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    average_pocket_time = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    number_of_times_blitzed = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    number_of_times_hurried = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    number_of_times_hit = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    number_of_times_pressured = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    percent_of_times_pressured = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    scrambles = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_per_scramble = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_attempts = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_first_downs = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    def __str__(self):
        return f"{self.player} - Week {self.week}"

class weekly_rb_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    opp = models.CharField(max_length=255, null=True, blank=True)
    rushing_attempts = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_first_downs = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    targets = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receiving_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receiving_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    catch_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_per_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    first_down_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receiving_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_before_contact_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_after_contact_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    broken_tackles = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    attempts_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_before_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_before_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_after_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_after_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    average_depth_of_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receptions_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    number_of_drops = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    drop_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    interceptions_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    qbr_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)


    def __str__(self):
        return f"{self.player} - Week {self.week}"

class weekly_wr_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    opp = models.CharField(max_length=255, null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    targets = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receiving_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receiving_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    catch_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_per_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    first_down_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receiving_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_before_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_before_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_after_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_after_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    average_depth_of_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    broken_tackles = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receptions_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    number_of_drops = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    drop_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    interceptions_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    qbr_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)


    def __str__(self):
        return f"{self.player} - Week {self.week}"

class weekly_te_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    opp = models.CharField(max_length=255, null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    targets = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receiving_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receiving_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    catch_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_per_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    first_down_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receiving_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_before_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_before_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_after_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    yards_after_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    average_depth_of_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    broken_tackles = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    receptions_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    number_of_drops = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    drop_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    interceptions_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    qbr_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)



    def __str__(self):
        return f"{self.player} - Week {self.week}"

class avg_qb_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    game_number = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    games_played = models.IntegerField(null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    date = models.CharField(max_length=255, null=True, blank=True)
    age = models.CharField(max_length=255, null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    result = models.CharField(max_length=255, null=True, blank=True)
    avg_completions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_passing_attempts = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_incompletions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_completion_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_passing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_passing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_interceptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_number_of_pick_6 = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_touchdown_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_interception_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_passer_rating = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_sacks = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_sack_yards_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_sack_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_passing_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_air_yards_per_pass_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_passing_adjusted_net_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_per_completion = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_passing_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_intended_air_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_intended_air_yards_per_pass_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_completed_air_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_completed_air_yards_per_completion = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_completed_air_yards_per_pass_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_after_catch = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_after_catch_per_completion = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_passes_batted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_throw_aways = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_spikes = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_passes_dropped = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_percent_of_passes_dropped = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_bad_throws = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_bad_throw_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_passes_on_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_percent_of_passes_on_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_average_pocket_time = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_number_of_times_blitzed = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_number_of_times_hurried = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_number_of_times_hit = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_number_of_times_pressured = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_percent_of_times_pressured = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_scrambles = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_per_scramble = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_attempts = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_first_downs = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)


    def __str__(self):
        return f"{self.player} - Week {self.week}"

class avg_rb_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    games_played = models.IntegerField(null=True, blank=True)
    avg_rushing_attempts = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_first_downs = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_targets = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_receiving_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_receiving_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_catch_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_per_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_first_down_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_receiving_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_before_contact_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_after_contact_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_broken_tackles = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_attempts_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_before_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_before_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_after_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_after_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_average_depth_of_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_receptions_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_number_of_drops = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_drop_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_interceptions_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_qbr_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)

    def __str__(self):
        return f"{self.player} - Week {self.week}"

class avg_wr_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    games_played = models.IntegerField(null=True, blank=True)
    avg_targets = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_receiving_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_receiving_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_catch_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_per_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_first_down_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_receiving_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_before_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_before_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_after_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_yards_after_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_average_depth_of_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_broken_tackles = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_receptions_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_number_of_drops = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_drop_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_interceptions_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_qbr_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)

    def __str__(self):
        return f"{self.player} - Week {self.week}"

class avg_te_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    games_played = models.IntegerField(null=True, blank=True)
    avg_targets = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_receptions = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_receiving_yards = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_yards_per_reception = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_receiving_touchdowns = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_catch_percentage = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_yards_per_target = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_first_down_receptions = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_receiving_success_rate = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_yards_before_contact = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_yards_before_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_yards_after_contact = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_yards_after_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_average_depth_of_target = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_broken_tackles = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_receptions_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_number_of_drops = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_drop_percentage = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_interceptions_when_targeted = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_qbr_when_targeted = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    avg_fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    avg_rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)

    def __str__(self):
        return f"{self.player} - Week {self.week}"



class total_qb_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    game_number = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    games_played = models.IntegerField(null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    date = models.CharField(max_length=255, null=True, blank=True)
    age = models.CharField(max_length=255, null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    opp = models.CharField(max_length=255, null=True, blank=True)
    result = models.CharField(max_length=255, null=True, blank=True)
    total_completions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_passing_attempts = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_incompletions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_completion_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_passing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_passing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_interceptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_number_of_pick_6 = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_touchdown_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_interception_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_passer_rating = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_sacks = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_sack_yards_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_sack_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_passing_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_air_yards_per_pass_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_passing_adjusted_net_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_per_completion = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_passing_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_intended_air_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_intended_air_yards_per_pass_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_completed_air_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_completed_air_yards_per_completion = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_completed_air_yards_per_pass_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_after_catch = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_after_catch_per_completion = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_passes_batted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_throw_aways = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_spikes = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_passes_dropped = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_percent_of_passes_dropped = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_bad_throws = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_bad_throw_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_passes_on_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_percent_of_passes_on_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_average_pocket_time = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_number_of_times_blitzed = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_number_of_times_hurried = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_number_of_times_hit = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_number_of_times_pressured = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_percent_of_times_pressured = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_scrambles = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_per_scramble = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_attempts = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_first_downs = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)

    def __str__(self):
        return f"{self.player} - Week {self.week}"

class total_rb_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    games_played = models.IntegerField(null=True, blank=True)
    total_rushing_attempts = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_yards_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_first_downs = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_targets = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_receiving_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_receiving_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_catch_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_per_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_first_down_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_receiving_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_before_contact_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_after_contact_per_attempt = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_broken_tackles = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_attempts_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_before_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_before_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_after_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_after_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_average_depth_of_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_receptions_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_number_of_drops = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_drop_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_interceptions_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_qbr_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)

    def __str__(self):
        return f"{self.player} - Week {self.week}"

class total_wr_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    games_played = models.IntegerField(null=True, blank=True)
    total_targets = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_receiving_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_receiving_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_catch_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_per_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_first_down_receptions = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_receiving_success_rate = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_before_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_before_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_after_contact = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_yards_after_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_average_depth_of_target = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_broken_tackles = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_receptions_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_number_of_drops = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_drop_percentage = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_interceptions_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_qbr_when_targeted = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)

    def __str__(self):
        return f"{self.player} - Week {self.week}"

class total_te_stats(models.Model):
    rank = models.IntegerField(null=True, blank=True)
    player = models.CharField(max_length=255, null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    games_played = models.IntegerField(null=True, blank=True)
    total_targets = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_receptions = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_receiving_yards = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_yards_per_reception = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_receiving_touchdowns = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_catch_percentage = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_yards_per_target = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_first_down_receptions = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_receiving_success_rate = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_yards_before_contact = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_yards_before_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2, null=True,
                                                                   blank=True)
    total_yards_after_contact = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_yards_after_contact_per_reception = models.DecimalField(max_digits=10, decimal_places=2, null=True,
                                                                  blank=True)
    total_average_depth_of_target = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_broken_tackles = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_receptions_per_broken_tackle = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_number_of_drops = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_drop_percentage = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_interceptions_when_targeted = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_qbr_when_targeted = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    total_fantasy_points = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_fumbles_lost = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_yards = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    total_rushing_touchdowns = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)

    def __str__(self):
        return f"{self.player} - Week {self.week}"


class weekly_defense_stats(models.Model):
    team = models.CharField(max_length=255, null=True, blank=True)
    week = models.IntegerField(null=True, blank=True)
    qb_fantasy_points_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    qb_passing_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    qb_rushing_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    qb_passing_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_qb_fantasy_points_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_qb_passing_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_qb_rushing_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_qb_passing_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    rb_fantasy_points_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    rb_rushing_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    rb_receiving_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    rb_rushing_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    rb_receiving_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_rb_fantasy_points_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_rb_rushing_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_rb_receiving_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_rb_rushing_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_rb_receiving_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    wr_fantasy_points_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    wr_rushing_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    wr_receiving_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    wr_rushing_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    wr_receiving_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_wr_fantasy_points_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_wr_rushing_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_wr_receiving_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_wr_rushing_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_wr_receiving_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    te_fantasy_points_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    te_rushing_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    te_receiving_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    te_rushing_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    te_receiving_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_te_fantasy_points_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_te_rushing_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_te_receiving_yards_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_te_rushing_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cumulative_te_receiving_touchdowns_allowed = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)


